// Generated by scripts/gen-web.ts — do not edit. Run `npm run gen:web`.
window.SCAFFOLD_REGISTRY = {
  "templates": [
    {
      "id": "lib",
      "title": "TypeScript library",
      "hint": "tsc build, exports map, publishable package",
      "lang": [
        "TypeScript"
      ],
      "deps": [],
      "dev": [
        "@types/node",
        "typescript"
      ],
      "tree": [
        ".gitignore",
        "README.md",
        "package.json",
        "src/index.ts",
        "tsconfig.json"
      ]
    },
    {
      "id": "cli",
      "title": "CLI app",
      "hint": "citty commands, bin entry, interactive prompts",
      "lang": [
        "TypeScript"
      ],
      "deps": [
        "@clack/prompts",
        "citty"
      ],
      "dev": [
        "@types/node",
        "tsx",
        "typescript"
      ],
      "tree": [
        ".gitignore",
        "README.md",
        "package.json",
        "src/commands/hello.ts",
        "src/index.ts",
        "tsconfig.json"
      ]
    },
    {
      "id": "mcp",
      "title": "MCP server",
      "hint": "stdio Model Context Protocol server with zod-validated tools",
      "lang": [
        "TypeScript"
      ],
      "deps": [
        "@modelcontextprotocol/sdk",
        "zod"
      ],
      "dev": [
        "@types/node",
        "tsx",
        "typescript"
      ],
      "tree": [
        ".gitignore",
        "README.md",
        "package.json",
        "src/index.ts",
        "tsconfig.json"
      ]
    },
    {
      "id": "api",
      "title": "HTTP API service",
      "hint": "Hono router, typed config, health check",
      "lang": [
        "TypeScript"
      ],
      "deps": [
        "@hono/node-server",
        "dotenv",
        "hono"
      ],
      "dev": [
        "@types/node",
        "tsx",
        "typescript"
      ],
      "tree": [
        ".gitignore",
        "README.md",
        "package.json",
        "src/config.ts",
        "src/index.ts",
        "tsconfig.json"
      ]
    },
    {
      "id": "tauri",
      "title": "Tauri desktop app",
      "hint": "local-first just-app: React 19 + justui over a Rust backend, keychain, six themes",
      "lang": [
        "TypeScript",
        "Rust"
      ],
      "deps": [],
      "dev": [
        "@tauri-apps/cli",
        "cross-env",
        "typescript"
      ],
      "tree": [
        ".gitignore",
        "AGENTS.md",
        "README.md",
        "apps/web/index.html",
        "apps/web/package.json",
        "apps/web/postcss.config.cjs",
        "apps/web/src/App.tsx",
        "apps/web/src/lib/commands.test.ts",
        "apps/web/src/lib/commands.ts",
        "apps/web/src/lib/runtime.ts",
        "apps/web/src/main.tsx",
        "apps/web/src/styles/global.css",
        "apps/web/tailwind.config.cjs",
        "apps/web/tsconfig.json",
        "apps/web/vite.config.ts",
        "apps/web/vitest.config.ts",
        "package.json",
        "pnpm-workspace.yaml",
        "src-tauri/.gitignore",
        "src-tauri/Cargo.toml",
        "src-tauri/build.rs",
        "src-tauri/capabilities/default.json",
        "src-tauri/icons/128x128.png",
        "src-tauri/icons/128x128@2x.png",
        "src-tauri/icons/32x32.png",
        "src-tauri/icons/icon.ico",
        "src-tauri/icons/icon.png",
        "src-tauri/src/lib.rs",
        "src-tauri/src/main.rs",
        "src-tauri/tauri.conf.json"
      ]
    },
    {
      "id": "web",
      "title": "Consumer web product",
      "hint": "web-first: converting landing + accounts + payments, brand themes (service · utility · fintech · shop)",
      "lang": [
        "TypeScript"
      ],
      "deps": [],
      "dev": [
        "typescript"
      ],
      "tree": [
        ".gitignore",
        "README.md",
        "apps/web/index.html",
        "apps/web/package.json",
        "apps/web/postcss.config.cjs",
        "apps/web/src/App.tsx",
        "apps/web/src/Marketplace.tsx",
        "apps/web/src/main.tsx",
        "apps/web/src/styles/global.css",
        "apps/web/tailwind.config.cjs",
        "apps/web/tsconfig.json",
        "apps/web/vite.config.ts",
        "package.json",
        "pnpm-workspace.yaml"
      ]
    },
    {
      "id": "extension",
      "title": "Chrome extension",
      "hint": "Manifest V3: React popup, service worker, content script, typed message bus",
      "lang": [
        "TypeScript"
      ],
      "deps": [
        "@codellyson/justui",
        "@fontsource-variable/geist",
        "react",
        "react-dom"
      ],
      "dev": [
        "@types/chrome",
        "@types/react",
        "@types/react-dom",
        "@vitejs/plugin-react",
        "autoprefixer",
        "concurrently",
        "postcss",
        "tailwindcss",
        "typescript",
        "vite"
      ],
      "tree": [
        ".gitignore",
        "README.md",
        "package.json",
        "popup.html",
        "postcss.config.cjs",
        "public/icons/icon-128.png",
        "public/icons/icon-16.png",
        "public/icons/icon-32.png",
        "public/icons/icon-48.png",
        "public/manifest.json",
        "src/background/index.ts",
        "src/content/index.ts",
        "src/lib/messages.ts",
        "src/popup/Popup.tsx",
        "src/popup/main.tsx",
        "src/styles/global.css",
        "tailwind.config.cjs",
        "tsconfig.json",
        "vite.config.ts",
        "vite.content.config.ts"
      ]
    }
  ],
  "features": [
    {
      "id": "vitest",
      "title": "Vitest",
      "hint": "test runner with a passing example spec",
      "appliesTo": [
        "lib",
        "cli",
        "mcp",
        "api",
        "extension"
      ],
      "recommended": true,
      "requires": null,
      "byTemplate": {
        "lib": {
          "adds": [
            "test/smoke.test.ts",
            "vitest.config.ts"
          ],
          "deps": [],
          "dev": [
            "vitest"
          ],
          "patches": [],
          "note": null
        },
        "cli": {
          "adds": [
            "test/smoke.test.ts",
            "vitest.config.ts"
          ],
          "deps": [],
          "dev": [
            "vitest"
          ],
          "patches": [],
          "note": null
        },
        "mcp": {
          "adds": [
            "test/smoke.test.ts",
            "vitest.config.ts"
          ],
          "deps": [],
          "dev": [
            "vitest"
          ],
          "patches": [],
          "note": null
        },
        "api": {
          "adds": [
            "test/smoke.test.ts",
            "vitest.config.ts"
          ],
          "deps": [],
          "dev": [
            "vitest"
          ],
          "patches": [],
          "note": null
        },
        "extension": {
          "adds": [
            "test/smoke.test.ts",
            "vitest.config.ts"
          ],
          "deps": [],
          "dev": [
            "vitest"
          ],
          "patches": [],
          "note": null
        }
      }
    },
    {
      "id": "github-actions",
      "title": "GitHub Actions CI",
      "hint": "typecheck + build on push and PR; desktop release matrix for Tauri",
      "appliesTo": "*",
      "recommended": true,
      "requires": null,
      "byTemplate": {
        "lib": {
          "adds": [
            ".github/workflows/ci.yml"
          ],
          "deps": [],
          "dev": [],
          "patches": [],
          "note": null
        },
        "cli": {
          "adds": [
            ".github/workflows/ci.yml"
          ],
          "deps": [],
          "dev": [],
          "patches": [],
          "note": null
        },
        "mcp": {
          "adds": [
            ".github/workflows/ci.yml"
          ],
          "deps": [],
          "dev": [],
          "patches": [],
          "note": null
        },
        "api": {
          "adds": [
            ".github/workflows/ci.yml"
          ],
          "deps": [],
          "dev": [],
          "patches": [],
          "note": null
        },
        "tauri": {
          "adds": [
            ".github/workflows/ci.yml",
            ".github/workflows/release.yml"
          ],
          "deps": [],
          "dev": [],
          "patches": [],
          "note": null
        },
        "web": {
          "adds": [
            ".github/workflows/ci.yml"
          ],
          "deps": [],
          "dev": [],
          "patches": [],
          "note": null
        },
        "extension": {
          "adds": [
            ".github/workflows/ci.yml"
          ],
          "deps": [],
          "dev": [],
          "patches": [],
          "note": null
        }
      }
    },
    {
      "id": "auth",
      "title": "Bearer token auth",
      "hint": "hashed API tokens, requireAuth middleware, /auth/whoami",
      "appliesTo": [
        "api"
      ],
      "recommended": false,
      "requires": null,
      "byTemplate": {
        "api": {
          "adds": [
            ".env.example",
            "scripts/mint-token.ts",
            "src/auth.ts"
          ],
          "deps": [],
          "dev": [],
          "patches": [
            {
              "file": "src/index.ts",
              "anchor": "imports"
            },
            {
              "file": "src/index.ts",
              "anchor": "routes"
            }
          ],
          "note": "Run \"npm run token:mint\" and put the hash in .env as API_TOKEN_HASHES."
        }
      }
    },
    {
      "id": "docker",
      "title": "Dockerfile",
      "hint": "multi-stage build, non-root runtime user",
      "appliesTo": [
        "api",
        "mcp"
      ],
      "recommended": false,
      "requires": null,
      "byTemplate": {
        "mcp": {
          "adds": [
            ".dockerignore",
            "Dockerfile",
            "docker-compose.yml"
          ],
          "deps": [],
          "dev": [],
          "patches": [],
          "note": null
        },
        "api": {
          "adds": [
            ".dockerignore",
            "Dockerfile",
            "docker-compose.yml"
          ],
          "deps": [],
          "dev": [],
          "patches": [],
          "note": null
        }
      }
    },
    {
      "id": "release-script",
      "title": "Release script",
      "hint": "guarded version bump, tag, and push (justdb style)",
      "appliesTo": "*",
      "recommended": false,
      "requires": null,
      "byTemplate": {
        "lib": {
          "adds": [
            "scripts/release.sh"
          ],
          "deps": [],
          "dev": [],
          "patches": [],
          "note": "Run \"chmod +x scripts/release.sh\" if your platform needs it."
        },
        "cli": {
          "adds": [
            "scripts/release.sh"
          ],
          "deps": [],
          "dev": [],
          "patches": [],
          "note": "Run \"chmod +x scripts/release.sh\" if your platform needs it."
        },
        "mcp": {
          "adds": [
            "scripts/release.sh"
          ],
          "deps": [],
          "dev": [],
          "patches": [],
          "note": "Run \"chmod +x scripts/release.sh\" if your platform needs it."
        },
        "api": {
          "adds": [
            "scripts/release.sh"
          ],
          "deps": [],
          "dev": [],
          "patches": [],
          "note": "Run \"chmod +x scripts/release.sh\" if your platform needs it."
        },
        "tauri": {
          "adds": [
            "scripts/release.sh"
          ],
          "deps": [],
          "dev": [],
          "patches": [],
          "note": "Run \"chmod +x scripts/release.sh\" if your platform needs it."
        },
        "web": {
          "adds": [
            "scripts/release.sh"
          ],
          "deps": [],
          "dev": [],
          "patches": [],
          "note": "Run \"chmod +x scripts/release.sh\" if your platform needs it."
        },
        "extension": {
          "adds": [
            "scripts/release.sh"
          ],
          "deps": [],
          "dev": [],
          "patches": [],
          "note": "Run \"chmod +x scripts/release.sh\" if your platform needs it."
        }
      }
    },
    {
      "id": "web-surface",
      "title": "Web surface + local API",
      "hint": "run the same UI in a browser against a local Hono + node:sqlite API",
      "appliesTo": [
        "tauri"
      ],
      "recommended": false,
      "requires": null,
      "byTemplate": {
        "tauri": {
          "adds": [
            "apps/api/.env.example",
            "apps/api/package.json",
            "apps/api/src/db.ts",
            "apps/api/src/index.ts",
            "apps/api/tsconfig.json",
            "apps/web/src/lib/api-client.ts"
          ],
          "deps": [],
          "dev": [],
          "patches": [],
          "note": "Start the local API with \"pnpm dev:api\", then \"pnpm dev\" (browser) or \"pnpm tauri:dev\" (desktop)."
        }
      }
    },
    {
      "id": "mcp-surface",
      "title": "MCP server",
      "hint": "a thin stdio MCP server over the local API so agents can drive the app",
      "appliesTo": [
        "tauri"
      ],
      "recommended": false,
      "requires": [
        "web-surface"
      ],
      "byTemplate": {
        "tauri": {
          "adds": [
            "packages/mcp-server/package.json",
            "packages/mcp-server/src/index.ts",
            "packages/mcp-server/tsconfig.json"
          ],
          "deps": [],
          "dev": [],
          "patches": [],
          "note": "Build the MCP server (\"pnpm --filter @my-app/mcp-server build\") and register it: claude mcp add my-app -- node packages/mcp-server/dist/index.js"
        }
      }
    }
  ]
};
